### ISSUE TITLE
Nothing is playing

### ISSUE THREAD

**Issue by Starbix** [samcm/PlexTogether#2] opened 2016-12-04 15:20 UTC
<img width="1271" alt="bildschirmfoto 2016-12-04 um 16 18 06" src="https://cloud.githubusercontent.com/assets/12443257/20867115/4343f6d4-ba3d-11e6-9c4a-0b9e68101211.png">
It always display "Nothing", although it plays something. It also displays Mr. Robot which is played on no device. The console constantly says `Dont have valid metadata :(
home.js:188 ratingKey: 101`

**Comment by pureMidi** [comment] 2016-12-04 19:53
Are you using Plex Media Player? We know what the issue is and will push out a fix asap.

**Comment by Starbix** [comment] 2016-12-04 19:54
Yes

**Comment by pureMidi** [comment] 2016-12-04 20:01
Great. Short term use OpenPHT until we push a proper fix. PMP is a priority so we'll get this out as soon as possible.

**Comment by samcm** [comment] 2016-12-05 02:49
@Starbix This should be fixed in https://github.com/samcm/PlexTogether/commit/0dfa27c1799d76069dd9d46c3856eb22ca2e78cf

**Comment by Starbix** [comment] 2016-12-05 16:43
Fixed!

**Closed** 2016-12-05 18:31 UTC
