### ISSUE TITLE
Plex Media Player 3.20.6 update broke playback sync

### ISSUE THREAD

**Issue by liamreed** [samcm/PlexTogether#51] opened 2017-09-23 00:27 UTC
After the newest Plex Media Player update playback is not syncing between Windows PMP users in the same room

Server version: Version 1.9.1.4272 
Plex Media Player version: 3.20.6

**Comment by dgw** [comment] 2017-09-23 04:07
Are you sure that's Plex Media Player? The latest non-beta release of PMP is version 1.3.6.699-b7573ff0 (released Sep 22), and the latest beta is 2.1.0.74-8e24a8f4 (released last month).

Plex for Windows ([from the Windows Store](https://www.microsoft.com/en-us/store/p/plex/9wzdncrfj3q8)) appears to be at version 3.2.20, based on the changelog history. (I can't install it to check the latest version that way, as I'm on Windows 7 still.)

**Comment by samcm** [comment] 2017-09-23 07:31
Nice catch @dgw, I think you could be on the money.

@liamreed can you please confirm it's PMP?

**Comment by liamreed** [comment] 2017-09-23 11:27
https://i.imgur.com/CBkdRJG.png @dgw @samcm

**Comment by dgw** [comment] 2017-09-23 13:15
That's the Web UI. It has a different version number, independent of the application. You need to get the version number from the TV (fullscreen) UI, if that's where the issue is, or if you're playing media in the Web UI mode then it's a bug with that, not PMP.

**Comment by MrTroot** [comment] 2017-09-24 03:05
I'm having the same issue after updating PMP to 1.3.6 (Desktop web-client updated to 3.20.6). I'm using the desktop web mode, not the fullscreen TV mode, and the same PMS version.

**Comment by liamreed** [comment] 2017-09-24 03:20
It is indeed the Sep 22nd PMP update (1.3.6.699-b7573ff0 ) my bad. It was working perfectly up until the newest update in desktop web mode. 

It still seems to work if the host of the room is using PMP while the other person in the room uses the plextogether web player.

**Comment by samcm** [comment] 2017-09-24 04:59
Ok sweet. I've just upgraded to that PMP version and can see similar issues. My Plex servers are on different versions as well so we can probably rule that out. 

For some reason PMP is still returning `HTTP 200` with a valid response to the commands PT is sending. I  wonder if they've added something to the protocol without documenting it. iOS app still works though so I'll try and spend some time figuring out why that's the case to fix this.

In the meantime running PMP in fullscreen mode seems to fix the problem if PTPlayer/transcoding isn't an option.

**Comment by samcm** [comment] 2017-09-24 06:03
Fixed in latest commit, will deploy on app.plextogether.com within the next few hours

**Closed by samcm** 2017-09-24 06:03 UTC
